### ISSUE TITLE
Cannot run with BERT

### ISSUE THREAD

**Issue by Cuberick-Orion** [yahoo/maaf#1]
When running with bert, I encountered two bugs:

* Missing a layer `self.text_projection_layer` in `class ImgTextCompositionBase` - suspect it is to project the text features from `dim=768` to `dim=512` which is the hidden dimension;

* Need to convert float to long for `text_mask` in `img_text_composition_models.py` Line 240 by `.long()`.

Both are simple fix but in case if the author disagrees with my deduction on the projection layer I am posting it here.

**Comment by emdodds** [comment]
Thanks for your interest in the code, and sorry we didn't properly test this configuration in the public version. I've just pushed an update that fixes the problem, and which I believe is exactly the changes you suggested.
